version: 2.1
orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  build: 
    docker:
      - image: cimg/base:stable
    working_directory: ~/$CIRCLE_WORKING_DIRECTORY
    steps:
      - node/install
      - run :
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run : 
          name: Front-End Build
          command: |
            npm run frontend:build
      - run :
          name: Install Back-End Dependencies
          command: |
            npm run backend:install
      - run :
          name: Back-End Build
          command: |
            npm run backend:build
