version: 2.1
orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Front-End Install 
          command: |
            npm run frontend:install
            filters:
              branches:
                only:
                  - main
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
            filters:
              branches:
                only:
                  - main
      - run:
          name: Get and install node version manager.
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            filters:
              branches:
                only:
                  - main
      - run:
          name: Install Node version 14 using NVM
          command: |
            nvm install 14 
            filters:
              branches:
                only:
                  - main
      - run:
          name: Use Node version 14
          command: | 
            nvm use 14
            filters:
              branches:
                only:
                  - main
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
            filters:
              branches:
                only:
                  - main
            
      - run:
          name: Back-End Build 
          command: |
            npm run backend:build
            filters:
              branches:
                only:
                - main
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
            filters:
              branches:
                only:
                  - main
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
            filters:
              branches:
                only:
                  - main